# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: user
    build: .
    command: gunicorn -b 0.0.0.0:5000 user.wsgi:app
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=mongodb://localhost:27017/user
      - CELERY_BROKER_URL=redis://localhost:6379/1
      - CELERY_RESULT_BACKEND_URL=redis://localhost:6379/2
    volumes:
      - ./user:/code/user
      - ./db/:/db/
    ports:
      - "5000:5000"
  redis:
    image: redis
  celery:
    image: user
    command: "celery worker -A user.celery_app:app"
    env_file:
      - ./.flaskenv
    volumes:
      - .:/code
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND_URL=redis://redis:6379/2
