# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: bubble
    build: .
    command: gunicorn -b 0.0.0.0:5000 bubble.wsgi:app
    env_file:
      - ./.envs/.local/.flask
#    environment:
#      - DATABASE_URI=mongodb://localhost:27017/bubble
#      - CELERY_BROKER_URL=redis://localhost:6379/1
#      - CELERY_RESULT_BACKEND_URL=redis://localhost:6379/2
    volumes:
      - ./bubble:/code/bubble
      - ./db/:/db/
    ports:
      - "5000:5000"
  redis:
    image: redis
  celery:
    image: bubble
    command: "celery worker -A bubble.celery_app:app"
    env_file:
      - ./.envs/.local/.flask
    volumes:
      - .:/code
    depends_on:
      - redis
