# WARNING: this file is not suitable for production, please use with caution
version: '3'

networks:
  private:
  public:
    external:
      name: bubble_infrastructure_bubble

services:
  web:
    image: bubble
    build: .
    command: gunicorn -b 0.0.0.0:5001 bubble.wsgi:app
    env_file:
      - ./.envs/.local/.flask
    #    environment:
    #      - DATABASE_URI=mongodb://localhost:27017/bubble
    #      - CELERY_BROKER_URL=redis://localhost:6379/1
    #      - CELERY_RESULT_BACKEND_URL=redis://localhost:6379/2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=bubble"
      - "traefik.http.services.bubble.loadbalancer.server.port=5001"
      - "traefik.http.routers.bubble.rule=PathPrefix(`/api/v1/bubble`)"
      - "traefik.http.middlewares.bubble.forwardauth.address=http://192.168.112.128/api/v1/user_center/auth/"
      - "traefik.http.middlewares.bubble.forwardauth.authResponseHeaders=X-Auth-User-Id, X-Auth-User-Name"
      - "traefik.http.routers.bubble.middlewares=bubble@docker"
    volumes:
      - ./bubble:/code/bubble
      - ./db/:/db/
    ports:
      - "5001:5001"
    networks:
      - private
      - public
  redis:
    image: redis
  networks:
    - private
    - public
  celery:
    image: bubble
    command: "celery worker -A bubble.celery_app:app"
    env_file:
      - ./.envs/.local/.flask
    volumes:
      - .:/code
    networks:
      - private
      - public
    depends_on:
      - redis

